cout<<"**************************************Employee details**************************************"<<endl<<endl;
                cout<<"--------------------------------------------------------------------------------------------"<<endl;
                cout.fill(' ');
                cout.setf(ios :: left, ios :: adjustfield);
                cout.width(20);
                cout<<"Employee Id";
                cout<<"|  ";
                cout.fill(' ');
                cout.setf(ios :: left, ios :: adjustfield);
                cout.width(20);
                cout<<"Employee Name";
                cout<<"|  ";
                cout.fill(' ');
                cout.setf(ios :: left, ios :: adjustfield);
                cout.width(20);
                cout<<"Employee Gender";
                cout<<"|  ";
                cout.fill(' ');
                cout.setf(ios :: left, ios :: adjustfield);
                cout.width(20);
                cout<<"Employee Post";
                cout<<"|  ";
                cout.fill(' ');
                cout.setf(ios :: left, ios :: adjustfield);
                cout.width(10);
                cout<<"Employee Salary"<<endl;
                cout<<"----------------------------------------------------------------------------------------------------"<<endl;
